<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/base/base.css" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/common.css" />
    <!--[if lt IE 9]><script src="http://static.yidejia.com/min/b=js&f=core/html5.js"></script><![endif]-->

    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/column.css" />
</head>
<body>

<header class="header">
    <div class="header_top">
        <div class="header_top_inner">
            <nav>
                <a href="javascript:;">设为首页</a>
                <a href="javascript:;">收藏本站</a>
            </nav>
            <!-- JiaThis Button BEGIN -->
            <div class="jiathis_style">
                <span class="jiathis_txt">分享给朋友：</span>
                <a class="jiathis_button_qzone"></a>
                <a class="jiathis_button_tsina"></a>
                <a class="jiathis_button_tqq"></a>
                <a class="jiathis_button_weixin"></a>
                <a class="jiathis_button_renren"></a>
                <a class="jiathis_button_xiaoyou"></a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                <a class="jiathis_counter_style"></a>
            </div>
            <!-- JiaThis Button END -->
        </div>
    </div>
    <div class="header_center s_bb">
        <div class="header_center_inner">
            <a class="e_logo" href=""><img src="http://images.yidejia.com/images/stationGroup/private/common/logo.png" alt=""></a>
            <h1 class="e_column">爱情</h1>
            <nav class="l_list">
                <a href="">单身季节</a>
                <a href="">恋爱ing</a>
                <a href="">婚姻堡垒</a>
                <a href="">边缘情感</a>
            </nav>
        </div>
    </div>
</header>

<div class="container">
    <nav class="navigation">
        <a href="">私密网首页</a>
        <i>&gt;</i>
        <em>爱情</em>
    </nav>
    <section class="section">
        <div class="t_column t_carousel J_carousel">
            <div class="u_screen J_screen">
                <ol class="u_film J_film">
                    <li class="u_film_item">
                        <a class="e_img" href=""><img src="http://img1.atido.com/8/2015/02/14/8745615ec05.png" alt=""></a>
                    </li>
                    <li class="u_film_item">
                        <a class="e_img" href=""><img src="http://img1.atido.com/8/2015/02/14/8745615ec05.png" alt=""></a>
                    </li>
                    <li class="u_film_item">
                        <a class="e_img" href=""><img src="http://img1.atido.com/8/2015/02/14/8745615ec05.png" alt=""></a>
                    </li>
                    <li class="u_film_item">
                        <a class="e_img" href=""><img src="http://img1.atido.com/8/2015/02/14/8745615ec05.png" alt=""></a>
                    </li>
                    <li class="u_film_item">
                        <a class="e_img" href=""><img src="http://img1.atido.com/8/2015/02/14/8745615ec05.png" alt=""></a>
                    </li>
                </ol>
            </div>
            <a class="u_prev J_prev" href="javascript:;"></a>
            <a class="u_next J_next" href="javascript:;"></a>
            <div class="u_page J_page">
                <a href="javascript:;">1</a>
                <a href="javascript:;">2</a>
                <a href="javascript:;">3</a>
                <a href="javascript:;">4</a>
                <a href="javascript:;">5</a>
            </div>
        </div>
        <div class="t_column m_focus">
            <h2>TODAY’S FOCUS</h2>
            <ol class="c_focus_ol">
                <li class="l_text">
                    <h3><a href="">不是所有情史都能对男人坦白</a></h3>
                    <p class="t_p">男人的爱总是沉默的，他们不善于用嘴巴把心底的话出来，此时有些女人就因此抓狂。既然很简单，下...</p>
                </li>
                <li class="l_text">
                    <h3><a href="">不是所有情史都能对男人坦白</a></h3>
                    <p class="t_p">男人的爱总是沉默的，他们不善于用嘴巴把心底的话出来，此时有些女人就因此抓狂。既然很简单，下...</p>
                </li>
                <li class="l_text">
                    <h3><a href="">不是所有情史都能对男人坦白</a></h3>
                    <p class="t_p">男人的爱总是沉默的，他们不善于用嘴巴把心底的话出来，此时有些女人就因此抓狂。既然很简单，下...</p>
                </li>
                <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
            </ol>
        </div>
        <div class="t_column">
            <form class="t_form" action="">
                <input type="text" placeholder="搜索" />
                <button type="submit">&#xe698;</button>
            </form>
            <h2 class="t_title"><b>每日热点</b></h2>
            <ol class="t_friendship">
                <li>
                    <a href="">
                        <img src="http://img1.atido.com/7/2015/02/09/c1b980b43a4.jpg" alt="">
                        <span>男人7表现 看他心里有没有你</span>
                    </a>
                </li>
                <li class="t_list s_w"><a href="">我上夜班期间妻带情</a></li>
                <li class="t_list s_w"><a href="">我上夜班期间妻带情</a></li>
                <li class="t_list s_w"><a href="">我上夜班期间妻带情</a></li>
                <li class="t_list s_w"><a href="">我上夜班期间妻带情</a></li>
                <li class="t_list s_w"><a href="">我上夜班期间妻带情</a></li>
            </ol>
        </div>
    </section>
    <section class="section">
        <div class="section_left">
            <div class="m_column_item">
                <header class="t_header">
                    <h2 class="s_fz">单身季节</h2>
                    <a href="">More&gt;</a>
                </header>
                <ol class="c_season">
                    <li>
                        <a href=""><img src="http://img1.atido.com/7/2015/02/09/c1b980b43a4.jpg!140.105" alt="" title=""></a>
                    </li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                </ol>
            </div>
            <div class="m_column_item">
                <header class="t_header">
                    <h2 class="s_fz">恋爱ing</h2>
                    <a href="">More&gt;</a>
                </header>
                <ol class="c_season">
                    <li>
                        <a href=""><img src="http://img1.atido.com/7/2015/02/09/c1b980b43a4.jpg!140.105" alt="" title=""></a>
                    </li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                </ol>
            </div>
            <div class="m_column_item">
                <header class="t_header">
                    <h2 class="s_fz">婚姻堡垒</h2>
                    <a href="">More&gt;</a>
                </header>
                <ol class="c_season">
                    <li>
                        <a href=""><img src="http://img1.atido.com/7/2015/02/09/c1b980b43a4.jpg!140.105" alt="" title=""></a>
                    </li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                </ol>
            </div>
            <div class="m_column_item">
                <header class="t_header">
                    <h2 class="s_fz">边缘情感</h2>
                    <a href="">More&gt;</a>
                </header>
                <ol class="c_season">
                    <li>
                        <a href=""><img src="http://img1.atido.com/7/2015/02/09/c1b980b43a4.jpg!140.105" alt="" title=""></a>
                    </li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                    <li class="t_list"><a href="">我上夜班期间妻带情</a></li>
                </ol>
            </div>
        </div>
        <div class="section_right">
            <header class="t_header">
                <h2>情感百科</h2>
            </header>
            <nav class="t_nav">
                <?php foreach((array)$tag as $key=>$val){ ?>
                    <a href="/tag/<?php echo $val['slug']; ?>"><?php echo $val['name']; ?></a>
                <?php } ?>
            </nav>
        </div>
    </section>
</div>

<footer class="footer">
    <h1>精选内容</h1>
    <table class="footer_center">
        <tbody>
        <tr>
            <th><a href="">爱情</a></th>
            <th><a href="">友情</a></th>
            <th><a href="">婆媳</a></th>
            <th><a href="">亲情</a></th>
            <th><a href="">星座</a></th>
            <th><a href="">工作</a></th>
        </tr>
        <tr>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
                <a href="">外遇</a>
                <a href="">出轨</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="footer_bottom">
        <p>十万个护肤小妙招精心挑选最有效的美容护肤小窍门，为你解决常见的护肤问题。做最专业的护肤专家，十万个护肤小妙招。</p>
        <p>版权所有 © <a href="">smilady.com</a> 私密网</p>
    </div>
</footer>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/base/base.min.js"></script>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/stationGroup/private/common.js"></script>
<script type="text/javascript" charset="utf-8" src="http://v3.jiathis.com/code/jia.js"></script>
</body>
</html>