<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/base/base.css" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/common.css" />
    <!--[if lt IE 9]><script src="http://static.yidejia.com/min/b=js&f=core/html5.js"></script><![endif]-->

    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/list.css" />
</head>
<body>

<header class="header">
    <div class="header_top">
        <div class="header_top_inner">
            <nav>
                <a href="javascript:;">设为首页</a>
                <a href="javascript:;">收藏本站</a>
            </nav>
            <!-- JiaThis Button BEGIN -->
            <div class="jiathis_style">
                <span class="jiathis_txt">分享给朋友：</span>
                <a class="jiathis_button_qzone"></a>
                <a class="jiathis_button_tsina"></a>
                <a class="jiathis_button_tqq"></a>
                <a class="jiathis_button_weixin"></a>
                <a class="jiathis_button_renren"></a>
                <a class="jiathis_button_xiaoyou"></a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                <a class="jiathis_counter_style"></a>
            </div>
            <!-- JiaThis Button END -->
        </div>
    </div>
    <div class="header_center s_bg">
        <div class="header_center_inner">
            <a class="e_logo" href="/"><img src="http://images.yidejia.com/images/stationGroup/private/common/logo_2.png" alt=""></a>
            <div class="u_dls">
                <?php foreach($configPage as $key=>$val){ ?>
                    <dl>


                        <dt><a href="/<?php echo $val['slug']; ?>"><?php echo $val['name']; ?></a></dt>
                        <?php foreach($val['list'] as $k=>$v){ ?>
                            <dd><a href="/list/<?php echo $v['slug']; ?>"><?php echo $v['name']; ?></a></dd>
                        <?php } ?>

                    </dl>
                <?php } ?>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <nav class="navigation">
        <a href="/">私密网首页</a>
        <i>&gt;</i>
        <a>标签</a>
        <i>&gt;</i>
        <em><?php echo $name; ?></em>
    </nav>

    <section class="section">
        <div class="section_left">
            <header class="c_listTitle">
                <h2><?php echo $class['name'];?></h2>
                <p><?php echo $class['description'];?></p>
            </header>
            <div class="m_list">
                <ol>
                    <?php foreach((array)$data as $key=>$val){ ?>
                    <li>
                        <a class="e_img" href="/article/<?php echo $val['ID']; ?>" target="_blank"><img src="<?php echo $val['image']; ?>" alt="<?php echo $val['post_title']; ?>"></a>
                        <h3><a href="/article/<?php echo $val['ID']; ?>" target="_blank"><?php echo $val['post_title']; ?></a></h3>
                        <time><?php echo $val['post_date']; ?></time>
                        <p><?php echo $val['description']; ?><a href="/article/<?php echo $val['ID']; ?>" target="_blank">查看全文&gt;&gt;</a></p>
                        <nav>
                            <b>标签：</b>
                            <?php  foreach( $val['term'] as $v){ if($v['taxonomy'] == 'post_tag'){   ?>
                                <a href="/tag/<?php echo $v['slug']; ?>" target="_blank"><?php echo $v['name']; ?></a>
                            <?php  }  }  ?>
                        </nav>
                    </li>
                    <?php } ?>
                </ol>
                <div class="page">
                    <span class="page-item">上页</span>
                    <span class="page-item page-item_select">1</span>
                    <a class="page-item" href="/womenhf/?p=2">2</a>
                    <a class="page-item" href="/womenhf/?p=3">3</a>
                    <a class="page-item" href="/womenhf/?p=4">4</a>
                    <a class="page-item" href="/womenhf/?p=2">下页</a>
                </div>
            </div>
        </div>
        <div class="section_right">
            <h2 class="t_title"><b>热点推荐</b></h2>
            <ol class="t_friendship">
                <?php foreach((array)$hotData as $key=>$val){ ?>
                    <?php if($key == 0){ ?>
                    <li>
                        <a href="/article/<?php echo $val['ID']; ?>">
                            <img src="<?php echo $val['image']; ?>" alt="<?php echo $val['post_title']; ?>">
                            <span><?php echo $val['post_title']; ?></span>
                        </a>
                    </li>
                    <?php }else{ ?>
                    <li class="t_list s_w"><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></li>
                    <?php } ?>
                <?php } ?>
            </ol>
        </div>
    </section>
</div>

<footer class="footer">
    <h1>精选内容</h1>
    <table class="footer_center">
        <tbody>
        <tr>
            <th><a href="">爱情</a></th>
            <th><a href="">友情</a></th>
            <th><a href="">婆媳</a></th>
            <th><a href="">亲情</a></th>
            <th><a href="">星座</a></th>
            <th><a href="">工作</a></th>
        </tr>
        <tr>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
                <a href="">外遇</a>
                <a href="">出轨</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="footer_bottom">
        <p>十万个护肤小妙招精心挑选最有效的美容护肤小窍门，为你解决常见的护肤问题。做最专业的护肤专家，十万个护肤小妙招。</p>
        <p>版权所有 © <a href="">smilady.com</a> 私密网</p>
    </div>
</footer>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/base/base.min.js"></script>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/stationGroup/private/common.js"></script>
<script type="text/javascript" charset="utf-8" src="http://v3.jiathis.com/code/jia.js"></script>
</body>
</html>