<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/base/base.css" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/common.css" />
    <!--[if lt IE 9]><script src="http://static.yidejia.com/min/b=js&f=core/html5.js"></script><![endif]-->

    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/index.css" />
</head>
<body>

<header class="header">
    <div class="header_top">
        <div class="header_top_inner">
            <nav>
                <a href="javascript:;">设为首页</a>
                <a href="javascript:;">收藏本站</a>
            </nav>
            <!-- JiaThis Button BEGIN -->
            <div class="jiathis_style">
                <span class="jiathis_txt">分享给朋友：</span>
                <a class="jiathis_button_qzone"></a>
                <a class="jiathis_button_tsina"></a>
                <a class="jiathis_button_tqq"></a>
                <a class="jiathis_button_weixin"></a>
                <a class="jiathis_button_renren"></a>
                <a class="jiathis_button_xiaoyou"></a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                <a class="jiathis_counter_style"></a>
            </div>
            <!-- JiaThis Button END -->
        </div>
    </div>
    <div class="header_center">
        <div class="header_center_inner">
            <a class="e_logo" href=""><img src="http://images.yidejia.com/images/stationGroup/private/common/logo.png" alt=""></a>
            <ol>
                <li>
                    <a class="e_column" href="">首页</a>
                </li>
                <li>
                    <a class="e_column" href="">爱情</a>
                    <nav>
                        <a href="">单身季节</a>
                        <a href="">恋爱ing</a>
                        <a href="">婚姻堡垒</a>
                        <a href="">边缘情感</a>
                    </nav>
                </li>
                <li>
                    <a class="e_column" href="">友情</a>
                    <nav>
                        <a href="">房中闺蜜</a>
                        <a href="">兄弟连</a>
                        <a href="">蓝颜知己</a>
                    </nav>
                </li>
                <li>
                    <a class="e_column" href="">婆媳</a>
                    <nav>
                        <a href="">麻辣婆媳</a>
                    </nav>
                </li>
                <li>
                    <a class="e_column" href="">亲情</a>
                    <nav>
                        <a href="">父爱如山</a>
                        <a href="">母亲怀抱</a>
                        <a href="">手足之情</a>
                    </nav>
                </li>
                <li>
                    <a class="e_column" href="">工作职场</a>
                    <nav>
                        <a href="">八卦职场</a>
                        <a href="">“潜规则”</a>
                    </nav>
                </li>
                <li>
                    <a class="e_column" href="">每日星座</a>
                    <nav>
                        <a href="">星座解说</a>
                        <a href="">星座运程</a>
                    </nav>
                </li>
            </ol>
        </div>
    </div>
    <div class="header_bottom"></div>
</header>

<div class="container">
<section class="section">
    <div class="section_left t_carousel J_carousel">
        <div class="u_screen J_screen">
            <ol class="u_film J_film">
                <li class="u_film_item">
                    <a class="c_imgText" href="" target="_blank">
                        <img src="http://img2.atido.com/3/2015/01/08/a378fea96c8.jpg" alt="">
                                    <span>
                                        <big>总是单身？其实你没有那么想恋爱</big>
                                        <small>老是嚷嚷着要找个男人来恋爱，却总是找不到，总是单身，其实，你有没有想过……</small>
                                    </span>
                    </a>
                </li>
                <li class="u_film_item">
                    <a class="c_imgText" href="" target="_blank">
                        <img src="http://img2.atido.com/3/2015/01/08/a378fea96c8.jpg" alt="">
                                    <span>
                                        <big>总是单身？其实你没有那么想恋爱</big>
                                        <small>老是嚷嚷着要找个男人来恋爱，却总是找不到，总是单身，其实，你有没有想过……</small>
                                    </span>
                    </a>
                </li>
                <li class="u_film_item">
                    <a class="c_imgText" href="" target="_blank">
                        <img src="http://img2.atido.com/3/2015/01/08/a378fea96c8.jpg" alt="">
                                    <span>
                                        <big>总是单身？其实你没有那么想恋爱</big>
                                        <small>老是嚷嚷着要找个男人来恋爱，却总是找不到，总是单身，其实，你有没有想过……</small>
                                    </span>
                    </a>
                </li>
            </ol>
        </div>
        <a class="u_prev J_prev" href="javascript:;">&#xe696;</a>
        <a class="u_next J_next" href="javascript:;">&#xe697;</a>
        <div class="u_page J_page">
            <a href="javascript:;"></a>
            <a href="javascript:;"></a>
            <a href="javascript:;"></a>
        </div>
    </div>
    <div class="section_right">
        <form class="t_form" action="">
            <input type="text" placeholder="搜索" />
            <button type="submit">&#xe698;</button>
        </form>
        <h2 class="t_title"><b>情感百科</b></h2>
        <nav class="t_nav">
            <?php foreach((array)$tag as $key=>$val){ ?>
            <a href="/tag/<?php echo $val['slug']; ?>"><?php echo $val['name']; ?></a>
            <?php } ?>
        </nav>
    </div>
</section>
<section class="section">
    <div class="section_left">
        <div class="t_column">
            <header class="t_header">
                <h2>爱情</h2>
                <a href="">More&gt;</a>
            </header>
            <ol class="t_love">
                <?php  foreach((array)$loveData as $key=>$val){ ?>
                <li>
                    <a class="e_img" href="/article/<?php echo $val['ID']; ?>"><img src="<?php echo $val['image'];?>" alt="<?php echo $val['post_title']; ?>"></a>
                    <h3><a href="/article/<?php echo $val['ID']; ?>" title="<?php echo $val['post_title']; ?>"><?php echo $val['post_title']; ?></a></h3>
                    <p class="t_p s_mt"><?php echo $val['description']; ?></p>
                </li>
                <?php } ?>
            </ol>
        </div>
        <div class="t_column">
            <header class="t_header">
                <h2>友情</h2>
                <a href="">More&gt;</a>
            </header>
            <ol class="t_friendship">
                <?php  foreach((array)$friendlyData as $key=>$val){ ?>
                    <?php if($key == 0) {?>
                    <li>
                        <a href="/article/<?php echo $val['ID']; ?>">
                            <img src="<?php echo $val['image'];?>" alt="">
                            <span><?php echo $val['post_title']; ?></span>
                        </a>
                    </li>
                     <?php }else{ ?>
                    <li class="t_list"><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></li>
                    <?php } ?>
                <?php } ?>
            </ol>
        </div>
        <div class="t_column s_mt">
            <header class="t_header">
                <h2>婆媳</h2>
                <a href="">More&gt;</a>
            </header>
            <ol class="t_friendship">
                <?php  foreach((array)$pxData as $key=>$val){ ?>
                    <?php if($key == 0) {?>
                        <li>
                            <a href="/article/<?php echo $val['ID']; ?>">
                                <img src="<?php echo $val['image'];?>" alt="">
                                <span><?php echo $val['post_title']; ?></span>
                            </a>
                        </li>
                    <?php }else{ ?>
                        <li class="t_list"><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></li>
                    <?php } ?>
                <?php } ?>
            </ol>
        </div>
    </div>
    <div class="section_right">
        <header class="t_header">
            <h2>推荐TOP</h2>
        </header>
        <ol class="c_top">
            <?php  foreach((array)$stickyPosts as $key=>$val){ ?>
            <li>
                <h3><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></h3>
                <p class="t_p"><?php echo $val['description']; ?></p>
            </li>
            <?php } ?>
        </ol>
    </div>
</section>
<section class="section">
    <div class="t_column">
        <header class="t_header">
            <h2>亲情</h2>
            <a href="">More&gt;</a>
        </header>
        <ol class="t_family">
            <?php  foreach((array)$familyData as $key=>$val){ ?>
                <?php if($key == 0) {?>
                <li>
                    <a href="/article/<?php echo $val['ID']; ?>"><img src="<?php echo $val['image'];?>" alt="<?php echo $val['post_title']; ?>"></a>
                    <h3><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></h3>
                    <p class="t_p"><?php echo $val['description']; ?></p>
                </li>
                <?php }else{ ?>
                <li class="t_list"><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></li>
                <?php } ?>
            <?php } ?>
        </ol>
    </div>
    <div class="t_column">
        <header class="t_header">
            <h2>星座</h2>
            <a href="">More&gt;</a>
        </header>
        <ol class="t_family">
            <?php  foreach((array)$constellationData as $key=>$val){ ?>
                <?php if($key == 0) {?>
                    <li>
                        <a href="/article/<?php echo $val['ID']; ?>"><img src="<?php echo $val['image'];?>" alt="<?php echo $val['post_title']; ?>"></a>
                        <h3><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></h3>
                        <p class="t_p"><?php echo $val['description']; ?></p>
                    </li>
                <?php }else{ ?>
                    <li class="t_list"><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></li>
                <?php } ?>
            <?php } ?>
        </ol>
    </div>
    <div class="t_column">
        <header class="t_header">
            <h2>工作</h2>
            <a href="">More&gt;</a>
        </header>
        <ol class="t_family">
            <?php  foreach((array)$workData as $key=>$val){ ?>
                <?php if($key == 0) {?>
                    <li>
                        <a href="/article/<?php echo $val['ID']; ?>"><img src="<?php echo $val['image'];?>" alt="<?php echo $val['post_title']; ?>"></a>
                        <h3><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></h3>
                        <p class="t_p"><?php echo $val['description']; ?></p>
                    </li>
                <?php }else{ ?>
                    <li class="t_list"><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></li>
                <?php } ?>
            <?php } ?>
        </ol>
    </div>
</section>
</div>

<footer class="footer">
    <h1>精选内容</h1>
    <table class="footer_center">
        <tbody>
        <tr>
            <th><a href="">爱情</a></th>
            <th><a href="">友情</a></th>
            <th><a href="">婆媳</a></th>
            <th><a href="">亲情</a></th>
            <th><a href="">星座</a></th>
            <th><a href="">工作</a></th>
        </tr>
        <tr>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
                <a href="">外遇</a>
                <a href="">出轨</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="footer_bottom">
        <p>十万个护肤小妙招精心挑选最有效的美容护肤小窍门，为你解决常见的护肤问题。做最专业的护肤专家，十万个护肤小妙招。</p>
        <p>版权所有 © <a href="">smilady.com</a> 私密网</p>
    </div>
</footer>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/base/base.min.js"></script>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/stationGroup/private/common.js"></script>
<script type="text/javascript" charset="utf-8" src="http://v3.jiathis.com/code/jia.js"></script>
</body>
</html>