<!DOCTYPE HTML>
<html>
<head>
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/base/base.css" />
    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/common.css" />
    <!--[if lt IE 9]><script src="http://static.yidejia.com/min/b=js&f=core/html5.js"></script><![endif]-->

    <link type="text/css" charset="utf-8" rel="stylesheet" href="http://images.yidejia.com/css/stationGroup/private/info.css" />
</head>
<body>

<header class="header">
    <div class="header_top">
        <div class="header_top_inner">
            <nav>
                <a href="javascript:;">设为首页</a>
                <a href="javascript:;">收藏本站</a>
            </nav>
            <!-- JiaThis Button BEGIN -->
            <div class="jiathis_style">
                <span class="jiathis_txt">分享给朋友：</span>
                <a class="jiathis_button_qzone"></a>
                <a class="jiathis_button_tsina"></a>
                <a class="jiathis_button_tqq"></a>
                <a class="jiathis_button_weixin"></a>
                <a class="jiathis_button_renren"></a>
                <a class="jiathis_button_xiaoyou"></a>
                <a href="http://www.jiathis.com/share" class="jiathis jiathis_txt jtico jtico_jiathis" target="_blank"></a>
                <a class="jiathis_counter_style"></a>
            </div>
            <!-- JiaThis Button END -->
        </div>
    </div>
    <div class="header_center s_bg">
        <div class="header_center_inner">
            <a class="e_logo" href=""><img src="http://images.yidejia.com/images/stationGroup/private/common/logo_2.png" alt=""></a>
            <div class="u_dls">
                <dl>
                    <dt><a href="">爱情</a></dt>
                    <dd><a href="">单身季节</a></dd>
                    <dd><a href="">恋爱ing</a></dd>
                    <dd><a href="">婚姻堡垒</a></dd>
                    <dd><a href="">边缘情感</a></dd>
                </dl>
                <dl>
                    <dt><a href="">友情</a></dt>
                    <dd><a href="">房中闺蜜</a></dd>
                    <dd><a href="">兄弟连</a></dd>
                    <dd><a href="">蓝颜知己</a></dd>
                </dl>
                <dl>
                    <dt><a href="">婆媳</a></dt>
                    <dd><a href="">麻辣婆媳</a></dd>
                </dl>
                <dl>
                    <dt><a href="">亲情</a></dt>
                    <dd><a href="">父爱如山</a></dd>
                    <dd><a href="">母亲怀抱</a></dd>
                    <dd><a href="">手足之情</a></dd>
                </dl>
                <dl>
                    <dt><a href="">工作职场</a></dt>
                    <dd><a href="">八卦职场</a></dd>
                    <dd><a href="">“潜规则”</a></dd>
                </dl>
                <dl>
                    <dt><a href="">每日星座</a></dt>
                    <dd><a href="">星座解说</a></dd>
                    <dd><a href="">星座运程</a></dd>
                </dl>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <nav class="navigation">
        <a href="/">私密网首页</a>
        <i>&gt;</i>
        <a href="/<?php  foreach( $term as $v){ if($v['taxonomy'] == 'category'){  echo $v['slug'];  }  }  ?>"><?php  foreach( $term as $v){ if($v['taxonomy'] == 'category'){  echo $v['name'];  }  }  ?></a>
        <i>&gt;</i>
        <em><?php echo $data['post_title'];?></em>
    </nav>

    <section class="section">
        <div class="section_left">
            <div class="u_info">
                <h1 title="<?php echo $data['post_title'];?>"><?php echo $data['post_title'];?></h1>
                <section>
                    <span><?php echo $data['post_date'];?></span>
                    <span>来源：私密网</span>
                    <span>编辑：小亚</span>
                </section>
                <article><?php echo $data['post_content'];?></article>
                <nav>
                    <b>关键词：</b>
                    <?php  foreach( $term as $v){ if($v['taxonomy'] == 'post_tag'){   ?>
                        <a href="/tag/<?php echo $v['slug']; ?>" target="_blank"><?php echo $v['name']; ?></a>
                    <?php }} ?>
                </nav>
                <ol>
                    <li><a href="">上一篇：男人为何会和初恋爱火重燃</a></li>
                    <li><a href="">上一篇：男人为何会和初恋爱火重燃</a></li>
                </ol>
            </div>
            <div class="m_related">
                <header class="t_header">
                    <h2>相关阅读</h2>
                </header>
                <ol class="t_family">
                    <?php foreach($beData as $key=>$val){ ?>
                        <?php if($key == 0){ ?>
                    <li class="">
                        <a href="/article/<?php echo $val['ID']; ?>"><img src="<?php echo $val['images']; ?>" alt="<?php echo $val['post_title']; ?>"></a>
                        <h3><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></h3>
                        <p class="t_p"><?php echo $val['description']; ?></p>
                    </li>
                    <?php }else{ ?>
                    <li class="t_list s_w"><a href="/article/<?php echo $val['ID']; ?>"><?php echo $val['post_title']; ?></a></li>
                    <?php } ?>
                    <?php } ?>
                </ol>
            </div>
        </div>
        <div class="section_right">
            <h2 class="t_title"><b>编辑推荐</b></h2>
            <ol class="t_love">
                <?php foreach((array)$newsData as $key=>$val){ ?>

                    <li>
                        <a class="e_img" href="/article/<?php echo $val['ID']; ?>"><img src="<?php echo $val['image']; ?>" alt="<?php echo $val['post_title']; ?>"></a>
                        <h3><a href="/article/<?php echo $val['ID']; ?>" title="<?php echo $val['post_title']; ?>"><?php echo $val['post_title']; ?></a></h3>
                        <p class="t_p s_mt"><?php echo $val['description'];?></p>
                    </li>

                <?php } ?>
            </ol>
        </div>
    </section>
</div>

<footer class="footer">
    <h1>精选内容</h1>
    <table class="footer_center">
        <tbody>
        <tr>
            <th><a href="">爱情</a></th>
            <th><a href="">友情</a></th>
            <th><a href="">婆媳</a></th>
            <th><a href="">亲情</a></th>
            <th><a href="">星座</a></th>
            <th><a href="">工作</a></th>
        </tr>
        <tr>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
                <a href="">外遇</a>
                <a href="">出轨</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
            <td>
                <a href="">男上司</a>
                <a href="">男同事</a>
                <a href="">财产</a>
            </td>
        </tr>
        </tbody>
    </table>
    <div class="footer_bottom">
        <p>十万个护肤小妙招精心挑选最有效的美容护肤小窍门，为你解决常见的护肤问题。做最专业的护肤专家，十万个护肤小妙招。</p>
        <p>版权所有 © <a href="">smilady.com</a> 私密网</p>
    </div>
</footer>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/base/base.min.js"></script>
<script type="text/javascript" charset="utf-8" src="http://images.yidejia.com/js/stationGroup/private/common.js"></script>
<script type="text/javascript" charset="utf-8" src="http://v3.jiathis.com/code/jia.js"></script>
</body>
</html>